version: '3.3'

services:

   client:
    build: ./client
    restart: always
    
   server:
    build: ./server
    restart: always

   mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    
      
   